# Generated by Django 3.2 on 2021-06-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam_classifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
