# Generated by Django 3.2 on 2021-06-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam_classifier', '0002_blockedips'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
